add solution for 03-streams 01-limit-size-stream
js-tasks-ru/nodejs-20200914-2_vladimirvlad-68 pull request #2
Opened 2020-09-25 18:59 UTC by Vladislav37

2020-09-25 19:06 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Стрим с лимитом передачи данных
+ стрим передает поступающие данные без изменений
+ при превышении лимита выбрасывается ошибка
```

Добавляю преподавателя (@RidgeA) для код-ревью, посмотрим что он скажет :)

2020-09-27 20:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @RidgeA

2020-09-28 17:05 UTC, RidgeA requested changes

2020-09-28 17:05 UTC, RidgeA commented on 03-streams/01-limit-size-stream/LimitSizeStream.js
> +    try {
`try/catch` и `throw` тут лишнее, более правильно будет сразу вызвать callback-функцию с ошибкой.

При этом важно не забыть завершить выполнение текущей функции после вызова callback-функции

2020-09-28 20:05 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-09-29 20:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @RidgeA

2020-09-29 20:56 UTC, RidgeA approved these changes

2020-09-30 07:27 UTC, RidgeA approved these changes

2020-09-30 07:27 UTC, merged